(() => {
  "use strict";
  const CFG=window.MARTINS_CONFIG||{}, DEF=window.MARTINS_DEFAULTS||{};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const h=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const brl=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const S={on:false,view:"dashboard",site:{},products:[],readyOrders:[],customOrders:[],editId:null,image:undefined,enc:{}};
  let db=null;
  const STATUS=["novo","em andamento","confirmado","concluído","cancelado"];
  const TITLES={dashboard:"Dashboard","prod-ready":"Produtos — Pronta Entrega","prod-orders":"Produtos — Encomendas","ord-ready":"Pedidos — Pronta Entrega","ord-orders":"Pedidos — Encomendas",settings:"Configurações"};
  const DEFAULT_ENC={
    cakes:[
      {name:"Naked Cake",options:["06/08 pessoas","10/12 pessoas","15/20 pessoas","20/25 pessoas","25/30 pessoas","30/40 pessoas","40/50 pessoas","50/60 pessoas"],prices:[45,70,98,115,145,188,240,280],active:true},
      {name:"Chantininho",options:["06/08 pessoas","10/12 pessoas","15/20 pessoas","20/25 pessoas","25/30 pessoas","30/40 pessoas","40/50 pessoas","50/60 pessoas"],prices:[60,80,120,140,170,220,260,300],active:true}
    ],
    masses:["Amanteigado","Ninho","Chocolate","Baunilha","Coco","Limão"],
    fillings:["Ninho","Brigadeiro","Leite condensado","Oreo","Beijinho","Doce de leite","Limão"],
    extras:[["Abacaxi",10],["Morango",16],["Crocante de Castanha",10],["Kit Kat",12],["Geleia de Morango",16],["Ouro Branco",10],["Nutella",16],["Kinder Bueno",16]],
    personalizations:[["Topo simples",20],["Topo 3D",30],["Flores naturais",70]],
    brigadeiros:{classica:["Brigadeiro Tradicional","Brigadeiro Branco Ninho","Casadinho","Limão","Beijinho","Doce de Leite"],premium:["Ninho com Nutella","Moça Cremoso","Surpresa de Uva","Belga ao Leite","Belga Amargo","Creme Bruleé","Brigadeiro com Castanha","Doce de Leite com Castanha","Kit Kat","Oreo"],classicaPrices:[62.5,125],premiumPrices:[72.5,145],flavorLimit50:2,flavorLimit100:4},
    otherItems:[{name:"Petit Brownie",active:true,price:0},{name:"Mini Brownie Recheado",active:true,price:0},{name:"Bem Casado",active:true,price:0},{name:"Cupcakes",active:true,price:35}],
    kits:[{id:"k1",name:"Kit Festa 01",price:150,cake:"Chantininho 10/15 Pessoas",items:["04 Cupcakes","20 Petit Brownie","20 Docinhos"],active:true},{id:"k2",name:"Kit Festa 02",price:200,cake:"Chantininho 15/20 Pessoas",items:["05 Cupcakes","30 Petit Brownie","30 Docinhos"],active:true},{id:"k3",name:"Kit Festa 03",price:250,cake:"Chantininho 20/25 Pessoas",items:["08 Cupcakes","50 Petit Brownie","50 Docinhos"],active:true},{id:"k4",name:"Kit Festa 04",price:430,cake:"Chantininho 30/40 Pessoas",items:["10 Cupcakes","60 Petit Brownie","60 Docinhos"],active:true},{id:"k5",name:"Kit Festa 05",price:500,cake:"Chantininho 40/50 Pessoas",items:["12 Cupcakes","70 Petit Brownie","70 Docinhos"],active:true}]
  };
  function toast(msg,error=false){const t=$("#toast");t.textContent=msg;t.style.background=error?"#c0392b":"#2b7896";t.style.display="block";clearTimeout(t._t);t._t=setTimeout(()=>t.style.display="none",3500)}
  const site=k=>S.site[k]??DEF[k];
  function clone(x){return JSON.parse(JSON.stringify(x))}
  function mergeEnc(v){const x=clone(DEFAULT_ENC);if(!v||typeof v!=="object")return x;return {...x,...v,cakes:Array.isArray(v.cakes)?v.cakes:x.cakes,otherItems:Array.isArray(v.otherItems)?v.otherItems:x.otherItems,kits:Array.isArray(v.kits)?v.kits:x.kits,brigadeiros:{...x.brigadeiros,...(v.brigadeiros||{})}}}
  async function loadSite(){const {data,error}=await db.from("settings").select("value").eq("key","site").maybeSingle();if(error)throw error;S.site=data?.value||{}}
  async function saveSite(patch){const next={...S.site,...patch};const {error}=await db.from("settings").upsert({key:"site",value:next},{onConflict:"key"});if(error)throw error;S.site=next}
  async function loadEnc(){const {data,error}=await db.from("settings").select("value").eq("key","encomendas").maybeSingle();if(error&&error.code!=="PGRST116")throw error;S.enc=mergeEnc(data?.value)}
  async function saveEnc(){const {error}=await db.from("settings").upsert({key:"encomendas",value:S.enc},{onConflict:"key"});if(error)throw error;toast("Configuração de encomendas salva.")}
  async function loadProducts(){const {data,error}=await db.from("products").select("*").order("sort",{ascending:true,nullsFirst:false});if(error)throw error;S.products=data||[]}
  const area=p=>String(p.area||p.type||"").toLowerCase().startsWith("encom")?"encomendas":"pronta";
  async function loadOrders(){S.readyOrders=[];S.customOrders=[];let r=await db.from("orders").select("*").limit(300);if(!r.error)S.readyOrders=r.data||[];let c=await db.from("custom_cakes").select("*").limit(300);if(!c.error)S.customOrders=c.data||[]}
  function normCustom(o){const d=o.data&&typeof o.data==="object"?o.data:o;return {id:o.id,created_at:o.created_at,status:o.status||"novo",...d,__custom:true}}
  function finalPrice(p){return Number(p.price||0)*(1-Math.min(100,Math.max(0,Number(p.discount_percent||0)))/100)}
  function go(view){S.view=view;$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#title').textContent=TITLES[view];$('#side').classList.remove('open');$('#view').innerHTML='<div class="empty">Carregando...</div>';try{if(view.startsWith('ord')||view==='dashboard')loadOrders().then(()=>VIEWS[view]()).catch(e=>errView(e));else if(view==='prod-orders')loadEnc().then(()=>VIEWS[view]()).catch(e=>errView(e));else VIEWS[view]()}catch(e){errView(e)}}
  function errView(e){console.error(e);$('#view').innerHTML=`<div class="empty">Não foi possível carregar: ${h(e.message)}</div>`}
  function dashboardView(){const pr=S.products.filter(p=>area(p)==='pronta'),en=S.products.filter(p=>area(p)==='encomendas');$('#view').innerHTML=`<div class="stats"><div class="card stat"><strong>${S.products.length}</strong><span>Produtos cadastrados</span></div><div class="card stat"><strong>${pr.length}</strong><span>Pronta entrega</span></div><div class="card stat"><strong>${en.length}</strong><span>Produtos de encomendas</span></div><div class="card stat"><strong>${S.readyOrders.length}</strong><span>Pedidos pronta entrega</span></div><div class="card stat"><strong>${S.customOrders.length}</strong><span>Encomendas</span></div><div class="card stat"><strong>${[...S.readyOrders,...S.customOrders].filter(o=>String(o.status||'novo').toLowerCase().includes('novo')).length}</strong><span>Novos</span></div></div><div class="card"><h3 style="color:var(--pd)">Atalhos</h3><div class="acts"><button class="btn primary" data-go="prod-ready">+ Produto pronta entrega</button><button class="btn soft" data-go="prod-orders">Gerenciar encomendas</button><button class="btn soft" data-go="ord-ready">Pedidos pronta entrega</button><button class="btn soft" data-go="ord-orders">Encomendas recebidas</button><button class="btn soft" data-go="settings">Configurações</button></div></div>`}
  function productCard(p){const on=p.available!==false,d=Number(p.discount_percent||0);return `<article class="card prod"><div class="pimg">${p.image_url?`<img src="${h(p.image_url)}" alt="${h(p.name)}">`:'🧁'}</div><div class="pbody"><span class="tag">${h(p.category||'Sem classificação')}</span><span class="tag ${on?'ok':'off'}">${on?'Ativo':'Inativo'}</span><h4>${h(p.name)}</h4>${p.description?`<p>${h(p.description)}</p>`:''}<div class="price">${d?`<s>${brl(p.price)}</s>`:''}${brl(finalPrice(p))}</div></div><div class="pact"><button class="btn soft sm" data-act="edit" data-id="${h(p.id)}">Editar</button><button class="btn soft sm" data-act="toggle" data-id="${h(p.id)}">${on?'Desativar':'Ativar'}</button><button class="btn danger sm" data-act="del" data-id="${h(p.id)}">Excluir</button></div></article>`}
  function productsView(kind){const list=S.products.filter(p=>area(p)===kind),groups={};list.forEach(p=>(groups[p.category||'Sem classificação']??=[]).push(p));$('#view').innerHTML=`<div class="head"><div><h2>${kind==='pronta'?'Pronta Entrega':'Encomendas'}</h2><p class="muted">${list.length} produto(s) na tabela products.</p></div><div class="acts"><button class="btn primary" data-act="new" data-kind="${kind}">+ Adicionar produto</button></div></div>${kind==='encomendas'?'<div class="card" style="margin-bottom:16px"><b>Opções do formulário de encomendas</b><p class="small-note">Os bolos, kits, brigadeiros, massas, recheios, adicionais e outros itens abaixo são controlados separadamente do cardápio de pronta entrega.</p></div>':''}${list.length?Object.entries(groups).map(([c,a])=>`<h3 class="cat">${h(c)}</h3><div class="plist">${a.map(productCard).join('')}</div>`).join(''):'<div class="empty">Nenhum produto nesta área.</div>'}${kind==='encomendas'?encConfigView():''}`}
  function encConfigView(){const e=S.enc||mergeEnc();return `<div class="card"><div class="enctitle"><div><h2 style="margin:0;color:var(--pd)">Configuração de Encomendas</h2><p class="small-note">Esta seção alimenta diretamente o formulário público de encomendas.</p></div><button class="btn primary" data-act="save-enc">Salvar alterações</button></div><div class="encgrid">${e.cakes.map((c,i)=>`<div class="enccard"><h3>${h(c.name)}</h3>${c.options.map((o,j)=>`<div class="encrow"><input data-cake-name="${i}" data-cake-opt="${j}" value="${h(o)}"><input type="number" step="0.01" min="0" data-cake-price="${i}" data-cake-opt-price="${j}" value="${Number(c.prices?.[j]||0)}"></div>`).join('')}</div>`).join('')}</div><div class="enccard"><h3>Massas</h3><textarea id="enc-masses" rows="4">${h(e.masses.join('\n'))}</textarea><h3>Recheios</h3><textarea id="enc-fillings" rows="4">${h(e.fillings.join('\n'))}</textarea></div><div class="enccard"><h3>Adicionais</h3>${e.extras.map((x,i)=>`<div class="encrow"><input data-extra-name="${i}" value="${h(x[0])}"><input type="number" step="0.01" data-extra-price="${i}" value="${Number(x[1]||0)}"></div>`).join('')}</div><div class="enccard"><h3>Brigadeiros</h3><p class="small-note">Limite atual: ${e.brigadeiros.flavorLimit50} sabores para 50 unidades e ${e.brigadeiros.flavorLimit100} para 100 unidades.</p><label>Clássicos (um sabor por linha)<textarea id="enc-classica" rows="5">${h(e.brigadeiros.classica.join('\n'))}</textarea></label><label>Premium<textarea id="enc-premium" rows="5">${h(e.brigadeiros.premium.join('\n'))}</textarea></label><div class="encgrid"><label>Clássicos — 50 un.<input id="enc-cp50" type="number" step="0.01" value="${e.brigadeiros.classicaPrices[0]}"></label><label>Clássicos — 100 un.<input id="enc-cp100" type="number" step="0.01" value="${e.brigadeiros.classicaPrices[1]}"></label><label>Premium — 50 un.<input id="enc-pp50" type="number" step="0.01" value="${e.brigadeiros.premiumPrices[0]}"></label><label>Premium — 100 un.<input id="enc-pp100" type="number" step="0.01" value="${e.brigadeiros.premiumPrices[1]}"></label></div></div><div class="enccard"><h3>Outros itens</h3>${e.otherItems.map((x,i)=>`<div class="encrow"><input data-other-name="${i}" value="${h(x.name)}"><input type="number" step="0.01" data-other-price="${i}" value="${Number(x.price||0)}"></div>`).join('')}<p class="small-note">Preço 0 significa “sob consulta”.</p></div><button class="btn primary" data-act="save-enc">Salvar alterações</button></div>`}
  function readEncForm(){const e=clone(S.enc);e.cakes.forEach((c,i)=>{c.options.forEach((_,j)=>{const n=$(`[data-cake-name="${i}"][data-cake-opt="${j}"]`),p=$(`[data-cake-price="${i}"][data-cake-opt-price="${j}"]`);if(n)c.options[j]=n.value.trim();if(p)c.prices[j]=Number(p.value)||0})});e.masses=$('#enc-masses').value.split('\n').map(x=>x.trim()).filter(Boolean);e.fillings=$('#enc-fillings').value.split('\n').map(x=>x.trim()).filter(Boolean);e.extras=e.extras.map((x,i)=>[$(`[data-extra-name="${i}"]`).value.trim(),Number($(`[data-extra-price="${i}"]`).value)||0]).filter(x=>x[0]);e.brigadeiros.classica=$('#enc-classica').value.split('\n').map(x=>x.trim()).filter(Boolean);e.brigadeiros.premium=$('#enc-premium').value.split('\n').map(x=>x.trim()).filter(Boolean);e.brigadeiros.classicaPrices=[Number($('#enc-cp50').value)||0,Number($('#enc-cp100').value)||0];e.brigadeiros.premiumPrices=[Number($('#enc-pp50').value)||0,Number($('#enc-pp100').value)||0];e.otherItems=e.otherItems.map((x,i)=>({name:$(`[data-other-name="${i}"]`).value.trim(),active:true,price:Number($(`[data-other-price="${i}"]`).value)||0})).filter(x=>x.name);return e}
  function num(id){const v=$(id).value;return v===''?null:Number(String(v).replace(',','.'))}
  function fillCats(sel){const cats=[...new Set([...(Array.isArray(site('categories'))?site('categories'):[]),sel].filter(Boolean))];$('#f-cat').innerHTML='<option value="">Selecione</option>'+cats.map(c=>`<option>${h(c)}</option>`).join('');$('#f-cat').value=sel||''}
  function syncFields(){const r=$('#f-area').value==='pronta';$$('#pform .rd').forEach(x=>x.classList.toggle('hidden',!r))}
  function showPreview(src){$('#prev').src=src||'';$('#prev').classList.toggle('hidden',!src);$('#rmimg').classList.toggle('hidden',!src)}
  function openModal(p,kind){S.editId=p?p.id:null;S.image=undefined;$('#pform').reset();$('#mtitle').textContent=p?'Editar produto':'Novo produto';$('#f-area').value=p?area(p):kind;$('#f-name').value=p?.name||'';$('#f-price').value=p?.price??'';$('#f-disc').value=p?.discount_percent??'';$('#f-sort').value=p?.sort??'';$('#f-gram').value=p?.gramatura??'';$('#f-serve').value=p?.serve_ate??'';$('#f-desc').value=p?.description||'';$('#f-avail').checked=p?p.available!==false:true;$('#f-feat').checked=!!p?.featured;$('#f-appt').checked=!!p?.appointment_required;fillCats(p?.category||'');showPreview(p?.image_url);syncFields();$('#modal').classList.remove('hidden')}
  function compress(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error('Não foi possível ler a imagem.'));r.onload=()=>{const img=new Image();img.onerror=()=>rej(new Error('Imagem inválida.'));img.onload=()=>{const k=Math.min(1,1000/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*k);c.height=Math.round(img.height*k);c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)})}
  async function saveProduct(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const ready=$('#f-area').value==='pronta',name=$('#f-name').value.trim(),category=$('#f-cat').value,price=num('#f-price')??0;if(!name||!category)throw new Error('Informe nome e classificação.');const payload={name,category,price,area:ready?'cardapio':'encomendas',sort:num('#f-sort')??0,description:$('#f-desc').value.trim(),available:$('#f-avail').checked,discount_percent:ready?num('#f-disc')??0:0,gramatura:ready?num('#f-gram'):null,serve_ate:ready?num('#f-serve'):null,featured:ready&&$('#f-feat').checked,appointment_required:ready&&$('#f-appt').checked};if(S.image!==undefined)payload.image_url=S.image||null;const q=S.editId==null?db.from('products').insert(payload):db.from('products').update(payload).eq('id',S.editId);const {error}=await q;if(error)throw error;await loadProducts();$('#modal').classList.add('hidden');go(ready?'prod-ready':'prod-orders');toast('Produto salvo.')}catch(x){toast(x.message||'Erro ao salvar.',true)}finally{b.disabled=false}}
  async function productAction(act,id){const p=S.products.find(x=>String(x.id)===String(id));if(!p)return;try{if(act==='del'){if(!confirm(`Excluir "${p.name}"?`))return;const {error}=await db.from('products').delete().eq('id',p.id);if(error)throw error}else{const {error}=await db.from('products').update({available:p.available===false}).eq('id',p.id);if(error)throw error}await loadProducts();productsView(area(p));toast('Alteração salva.')}catch(x){toast(x.message,true)}}
  function fmt(v){if(v==null)return'';if(Array.isArray(v))return v.map(x=>typeof x==='object'?JSON.stringify(x):x).join('\n');if(typeof v==='object')return Object.entries(v).map(([k,x])=>`${k}: ${fmt(x)}`).join(' | ');return String(v)}
  function label(k){return String(k).replace(/[_-]+/g,' ').replace(/^./,c=>c.toUpperCase())}
  function orderHTML(o,kind,print=false){const custom=kind==='encomendas',d=custom?normCustom(o):o;const created=d.created_at?new Date(d.created_at):null;const customer=d.customer||d.customer_name||d.nome||d.name||'Cliente não informado';const phone=d.phone||d.whatsapp||d.customer_phone||'';const total=d.total??d.total_price??d['Total estimado']??'';const items=d.items||d.itens||d.produtos||d.pedido||d.order_items||d;const skip=new Set(['id','created_at','status','__custom','customer','customer_name','nome','name','phone','whatsapp','customer_phone','total','total_price']);const rest=Object.entries(d).filter(([k,v])=>!skip.has(k)&&fmt(v).trim()&&k!=='data');const status=d.status||'novo';return `<article class="card order"><div class="ohead"><div><h3>${h(customer)}</h3><span class="muted">${custom?'Encomenda':'Pedido'} #${h(d.id??'—')}</span></div>${print?`<strong>${h(status)}</strong>`:`<div class="acts noprint"><select class="status" data-act="status" data-kind="${kind}" data-id="${h(d.id)}">${STATUS.map(s=>`<option ${s===String(status).toLowerCase()?'selected':''}>${s}</option>`).join('')}</select><button class="btn soft sm" data-act="print" data-kind="${kind}" data-id="${h(d.id)}">🖨 Imprimir</button></div>`}</div><div class="ogrid"><div class="of"><b>Data</b><span>${created?created.toLocaleString('pt-BR'):''}</span></div><div class="of"><b>Telefone</b><span>${h(phone)}</span></div>${d.delivery_date||d['Data desejada']?`<div class="of"><b>Data desejada</b><span>${h(d.delivery_date||d['Data desejada'])}</span></div>`:''}<div class="of"><b>Itens / detalhes</b><span>${h(fmt(items))}</span></div>${rest.map(([k,v])=>`<div class="of"><b>${h(label(k))}</b><span>${h(fmt(v))}</span></div>`).join('')}</div>${total!==''&&typeof total!=='object'?`<div class="ototal">Total: ${brl(total)}</div>`:''}</article>`}
  function ordersView(kind){const list=kind==='pronta'?S.readyOrders:S.customOrders;$('#view').innerHTML=`<div class="head"><div><h2>${kind==='pronta'?'Pedidos — Pronta Entrega':'Pedidos — Encomendas'}</h2><p class="muted">${list.length} registro(s).</p></div><button class="btn soft noprint" data-act="printall" data-kind="${kind}">🖨 Imprimir lista</button></div>${list.length?list.map(o=>orderHTML(o,kind)).join(''):'<div class="empty">Nenhum registro encontrado.</div>'}`}
  async function setStatus(kind,id,status){const table=kind==='pronta'?'orders':'custom_cakes';const patch={status};let q=db.from(table).update(patch).eq('id',id);if(kind==='encomendas'&&table==='custom_cakes')q=db.from(table).update(patch).eq('id',id);const {error}=await q;if(error){toast(error.message,true);return}await loadOrders();ordersView(kind);toast('Status atualizado.')}
  function printOrders(list,kind){const w=window.open('','_blank','width=900,height=700');if(!w){toast('Janela de impressão bloqueada.',true);return}w.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Martins — ${kind}</title><style>body{font-family:Arial;padding:24px;color:#263238}h1{color:#2b7896;font-size:18px}.order{border:1px solid #ccc;border-radius:8px;padding:14px;margin:0 0 14px;break-inside:avoid}.ohead{display:flex;justify-content:space-between}.ogrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.of{border:1px solid #ddd;padding:7px;border-radius:6px}.of b{display:block;font-size:10px;color:#71808a;text-transform:uppercase}.of span{white-space:pre-wrap;font-size:13px}.ototal{text-align:right;font-weight:bold;margin-top:10px}</style></head><body><h1>Martins Confeitaria — ${kind==='pronta'?'Pedidos de Pronta Entrega':'Encomendas'}</h1>${list.map(o=>orderHTML(o,kind,true)).join('')}<script>onload=()=>print()<\/script></body></html>`);w.document.close()}
  function settingsView(){const hours=Array.isArray(site('hours'))?site('hours'):[];const days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];const about={...(DEF.about||{}),...(S.site.about||{})};$('#view').innerHTML=`<div class="head"><div><h2>Configurações</h2><p class="muted">Dados exibidos no site público.</p></div><button class="btn primary" data-act="save">Salvar alterações</button></div><div class="card sec"><h3>Contato</h3><div class="grid"><label>Nome<input id="s-name" value="${h(site('name'))}"></label><label>WhatsApp<input id="s-wa" value="${h(site('whatsapp'))}"></label><label>Instagram<input id="s-ig" value="${h(site('instagram'))}"></label><label>Google Maps<input id="s-maps" value="${h(site('maps'))}"></label><label>Google Avaliação<input id="s-review" value="${h(site('review'))}"></label><label class="full">Endereço<textarea id="s-addr" rows="5">${h((site('address')||[]).join('\n'))}</textarea></label></div></div><div class="card sec"><h3>Horários</h3>${days.map((d,i)=>{const x=hours[i]||{s:'closed'};return `<div class="hrow"><strong>${d}</strong><select data-hs="${i}"><option value="open" ${x.s==='open'?'selected':''}>Aberto</option><option value="closed" ${x.s==='closed'?'selected':''}>Fechado</option><option value="tbd" ${x.s==='tbd'?'selected':''}>A confirmar</option></select><input type="time" data-ho="${i}" value="${h(x.o||'')}"><input type="time" data-hc="${i}" value="${h(x.c||'')}"></div>`}).join('')}</div><div class="card sec"><h3>Nossa história</h3><div class="grid"><label>Título<input id="s-at" value="${h(about.title)}"></label><label>Frase<input id="s-aq" value="${h(about.quote)}"></label><label class="full">Texto<textarea id="s-atx" rows="9">${h(about.text||'')}</textarea></label></div></div><button class="btn primary" data-act="save">Salvar alterações</button>`}
  async function saveSettings(){try{const hours=[0,1,2,3,4,5,6].map(i=>({s:$(`[data-hs="${i}"]`).value,o:$(`[data-ho="${i}"]`).value,c:$(`[data-hc="${i}"]`).value}));if(hours.some(x=>x.s==='open'&&(!x.o||!x.c)))throw new Error('Preencha os horários dos dias abertos.');await saveSite({name:$('#s-name').value.trim(),whatsapp:$('#s-wa').value.replace(/\D/g,''),instagram:$('#s-ig').value.trim(),maps:$('#s-maps').value.trim(),review:$('#s-review').value.trim(),address:$('#s-addr').value.split('\n').map(x=>x.trim()).filter(Boolean),hours,about:{...(S.site.about||{}),title:$('#s-at').value,quote:$('#s-aq').value,text:$('#s-atx').value}});toast('Configurações salvas.')}catch(e){toast(e.message,true)}}
  const VIEWS={dashboard:dashboardView,'prod-ready':()=>productsView('pronta'),'prod-orders':()=>productsView('encomendas'),'ord-ready':()=>ordersView('pronta'),'ord-orders':()=>ordersView('encomendas'),settings:settingsView};
  document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)return go(nav.dataset.view);const g=e.target.closest('[data-go]');if(g)return go(g.dataset.go);if(e.target.closest('[data-close]')||e.target.id==='modal'){$('#modal').classList.add('hidden');return}const a=e.target.closest('[data-act]');if(!a||a.tagName==='SELECT')return;const {act,id,kind}=a.dataset;if(act==='new')openModal(null,kind);else if(act==='edit')openModal(S.products.find(p=>String(p.id)===String(id)));else if(act==='toggle'||act==='del')productAction(act,id);else if(act==='save')saveSettings();else if(act==='save-enc'){S.enc=readEncForm();saveEnc()}else if(act==='print')printOrders((kind==='pronta'?S.readyOrders:S.customOrders).filter(o=>String(o.id)===String(id)),kind);else if(act==='printall')printOrders(kind==='pronta'?S.readyOrders:S.customOrders,kind)});
  document.addEventListener('change',e=>{if(e.target.dataset?.act==='status')setStatus(e.target.dataset.kind,e.target.dataset.id,e.target.value)});
  async function enter(){if(S.on)return;S.on=true;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');try{await Promise.all([loadSite(),loadProducts(),loadEnc()]);go(S.view)}catch(e){S.on=false;$('#app').classList.add('hidden');$('#login').classList.remove('hidden');toast('Erro ao carregar painel: '+e.message,true)}}
  function init(){if(!window.supabase||!CFG.SUPABASE_URL||!CFG.SUPABASE_ANON_KEY){$('#loginMsg').textContent='Supabase/config.js não carregou.';return}db=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY);$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});b.disabled=false;$('#loginMsg').textContent=error?error.message:''});$('#logout').onclick=()=>db.auth.signOut();$('#refresh').onclick=async()=>{try{await Promise.all([loadSite(),loadProducts(),loadEnc(),loadOrders()]);go(S.view);toast('Painel atualizado.')}catch(e){toast(e.message,true)}};$('#burger').onclick=()=>$('#side').classList.toggle('open');$('#shade').onclick=()=>$('#side').classList.remove('open');$('#pform').onsubmit=saveProduct;$('#f-area').onchange=syncFields;$('#rmimg').onclick=()=>{S.image='';$('#f-photo').value='';showPreview('')};$('#f-photo').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{S.image=await compress(f);showPreview(S.image)}catch(x){toast(x.message,true)}};db.auth.onAuthStateChange((_,s)=>{if(s)setTimeout(enter,0);else{S.on=false;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}});db.auth.getSession().then(({data})=>data.session?enter():null)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
